name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        run: |
         ssh user@server-ip "cd /path/to/app && git pull && pkill -f 'uvicorn' && nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &"